### ISSUE TITLE
API gateway

### ISSUE THREAD

**Issue by katunilya** [unit-team-spbu/backend#27]
## Задача

Разработать микросервис `gateway`, ответственный за обработку и направление запросов по системе

## Технические Требования

Принимает http, отправляет в микросервисы rpc

- [x] sign in
- [x] sign up
- [x] получение событий для неавторизованного пользователя
- [x] получение топа мероприятий для зарегистрированного пользователя
- [x] создание/изменение интересов пользователя
- [x] обработка реакционных событий (лайк/дизлайк)
- [x] получение мероприятия 

## Материалы и ссылки

None

---

blocked #26

**Comment by SabinaAlieva** [comment]
- Добавить в избранное \ записаться на событие
- Изменение анкеты в ЛК
