### ISSUE TITLE
Получить список id всех пользователей

### ISSUE THREAD

**Issue by egorgorban** [unit-team-spbu/backend#43]
## Задача
Требуется разработать метод, который позволяет получить список _id_ всех зарегистрированных пользователей

## Технические Требования
Ничего не получая на вход, метод возвращает спсиок вида `[id_1, ..., id_n]` порядок _id_ не важен

## Материалы и ссылки
Метод удобнее реализовать в сервисе `auth`

**Comment by MaxKuznets0v** [comment]
Rpc метод `get_all_logins` был реализован в сервисе `auth`
