### ISSUE TITLE
задокументировать микросервисы

### ISSUE THREAD

**Issue by katunilya** [unit-team-spbu/backend#46]
## Задача

Требуется привести документацию для backend в порядок. В частности, документацию по отдельным микросервисам

## Технические Требования

Документация для каждого микросервиса (в файле `README.md` в папке микросервиса), должна быть приведена к следующему шаблону:

```md
# <название микросервиса>

<краткое описание предназначения микросервиса>

Название: `<название используемое nameko>`

Структура сервиса:

| Файл | Описание |
| ---- | -------- |
| ...  | ...      |

## API

### RPC

<для каждого rpc заропса представить пример вызова через nameko shell и описание входных и выходных параметров>

### HTTP

<для каждого http запроса представить его .rest описание-пример, лучше с примером выполнения запроса>

## Развертывание и запуска

<гайд для каждого docker-compose скрипта и запуска через nameko shell>
```

## Материалы и ссылки

Для единообразия формата md файлов, используйте следующие расширения для VS Code:

Name: Markdown All in One
Id: yzhang.markdown-all-in-one
Description: All you need to write Markdown (keyboard shortcuts, table of contents, auto preview and more)
Version: 3.3.0
Publisher: Yu Zhang
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=yzhang.markdown-all-in-one

Name: markdownlint
Id: davidanson.vscode-markdownlint
Description: Markdown linting and style checking for Visual Studio Code
Version: 0.37.2
Publisher: David Anson
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint

**Comment by egorgorban** [comment]
Описал все микросервисы в соответствующих файлах `README.md` в соответствии с шаблоном с использованием указанных расширений для `VS Code`.
