### ISSUE TITLE
Полная развертка сервиса на Хироку

### ISSUE THREAD

**Issue by SabinaAlieva** [unit-team-spbu/backend#71]

**Comment by MaxKuznets0v** [comment]
## Log
- При развертке сервиса на Heroku возникли трудности технического плана.
- Было решено перейти на Microsoft Azure.
- Образы всех микросервисов помещены на DockerHub в репозиторий `maxkuznets0v/aggregator`.
- Добавлен глобальный docker-compose для подтягивания образов из репозитория DockerHub.
- Сервер запущен по адресу: `20.52.2.24`.
- Открыты порты `8000-8013` для соответствующих микросервисов.
